#!/bin/sh
set -e
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop kcrap.service >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/kcrap" ] || [ -e "/etc/init/kcrap.conf" ]; then
	invoke-rc.d kcrap stop || exit $?
fi
# End automatically added section
